In [1]:
%matplotlib notebook

In [2]:
# import
from owcsimpy.geoobjects.models.typicalsimpleofficeenv_py import TypicalSimpleOfficeEnv_py as TypicalOfficeEnv
from owcsimpy.cir.freqdomaincir import FreqDomainCIR
from owcsimpy.cir.timedomaincir import TimeDomainCIR
from owcsimpy.cir.spheremodelcir import SphereModelCIR
from scipy.constants import speed_of_light
from owcsimpy.cir.cirutils import calcCIRFreqDom_fromMtx
import numpy as np

import matplotlib.pyplot as plt

import mpl_toolkits.mplot3d.art3d as art3d

from JSAnimation.IPython_display import display_animation
from matplotlib import animation

from owcsimpy.geoutils.mobility import getArrayMobility 

roomLength,roomWidth,roomHeight=4,3,3

In [3]:
randomMobModel = 'rwp'
activity = 'walking'
dimensions = (roomLength-0.2,roomWidth-0.2)
velocityMinMax = (0.1,1)
waitTimeMax = 1.
excludedArea = 1.8

In [68]:
traj = getArrayMobility(
                    randomMobModel=randomMobModel,
                    activity=activity,
                    dimensions=dimensions,
                    velocityMinMax=velocityMinMax,
                    waitTimeMax=waitTimeMax,
                    excludedArea=excludedArea)

In [5]:
traj

{'arrayLoc': array([[3.37616904, 1.92318326],
        [3.37586197, 1.92327883],
        [3.37555489, 1.9233744 ],
        ...,
        [1.78223006, 0.9099965 ],
        [1.78142399, 0.90970381],
        [1.78061791, 0.90941111]]),
 'arrayVel': array([0.32160356, 0.32160356, 0.32160356, ..., 0.85757012, 0.85757012,
        0.85757012]),
 'arrayTime': array([0.00000000e+00, 1.00000000e-03, 2.00000000e-03, ...,
        4.07001812e+01, 4.07011812e+01, 4.07021812e+01]),
 'arrayDir': array([ 2.83987249,  2.83987249,  2.83987249, ..., -2.79328363,
        -2.79328363, -2.79328363]),
 'arrayTheta0': array([-0.17971021, -0.17912136, -0.17853595, ..., -0.25984536,
        -0.25974113, -0.25962933]),
 'arrayOmega0': array([-0.19847622, -0.1985062 , -0.19854251, ..., -0.29693663,
        -0.29657345, -0.29620528])}

In [69]:
time = traj.get('arrayTime')
vel = traj.get('arrayVel')
# timecad = time

In [7]:
time

array([0.00000000e+00, 1.00000000e-03, 2.00000000e-03, ...,
       4.07001812e+01, 4.07011812e+01, 4.07021812e+01])

In [70]:
tmp = np.diff(vel)

In [12]:
np.find_common_type

array([0., 0., 0., ..., 0., 0., 0.])

In [71]:
idx = np.where(tmp != 0)

In [72]:
idx[0]

array([1258])

In [17]:
len(vel)

30096

In [27]:
x = np.where(tmp == 0.1)

In [31]:
len(x[0])

0

In [66]:
timecad = time
# for i in idx[0]:
#     print(i)
#     print((timecad[i+1]-timecad[i]))
#     timecad[i+1:] = timecad[i+1:]-(timecad[i+1]-timecad[i])

In [73]:
timecad[1259]-timecad[1258]

0.001000000000000334

In [55]:
np.alltrue(np.isclose(time,timecad))

True

In [61]:
np.sum(1000.*(timecad-time))

0.0